// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHqVTPZhRjtAMoTH4BPDgFCUJt-IhcqU8',
    appId: '1:177237399456:web:685ff737d87567d43336c5',
    messagingSenderId: '177237399456',
    projectId: 'nasaimagen',
    authDomain: 'nasaimagen.firebaseapp.com',
    storageBucket: 'nasaimagen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdiSGZmxLhQUwlULxtv565N3sEsETnvZg',
    appId: '1:177237399456:android:2120c3118819a2203336c5',
    messagingSenderId: '177237399456',
    projectId: 'nasaimagen',
    storageBucket: 'nasaimagen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ejgp10l8G23QGKE0P4yTkHHUUDtMSjY',
    appId: '1:177237399456:ios:d8529a3713ab5dac3336c5',
    messagingSenderId: '177237399456',
    projectId: 'nasaimagen',
    storageBucket: 'nasaimagen.appspot.com',
    androidClientId: '177237399456-eg1i9e1hfqognod8q5j8n1fijv18mm8m.apps.googleusercontent.com',
    iosClientId: '177237399456-icra0asue1g0i8ulvqnls614dci8vdrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasaimagen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ejgp10l8G23QGKE0P4yTkHHUUDtMSjY',
    appId: '1:177237399456:ios:abdd155431fb809c3336c5',
    messagingSenderId: '177237399456',
    projectId: 'nasaimagen',
    storageBucket: 'nasaimagen.appspot.com',
    androidClientId: '177237399456-eg1i9e1hfqognod8q5j8n1fijv18mm8m.apps.googleusercontent.com',
    iosClientId: '177237399456-8eq2v9990b5lp1jpm3opq3kb13lol04h.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasaimagen.RunnerTests',
  );
}
